version: '3.0' # specify docker-compose version
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: client # specify the directory of the Dockerfile
  ports:
  - "8080:80" # specify port mapping
 
 express: # name of the second service
  build: server # specify the directory of the Dockerfile
  environment:
  - MONGO_URL=mongodb://localhost:27017/accessiBe
  ports:
  - "3000:3000" #specify ports mapping
  depends_on:
  - mongo # link this service to the database service
 
 mongo: # name of the third service
  image: mongo # specify image to build container from
  ports:
  - "27017:27017" # specify port forwarding